---
# App defines the identity of this application's executable
# source code. That is the source code minus any configuration.
App:
  # SourceRepo is the canonical name of the source code repo that contains
  # the executable code for this application. The last path segment
  # of the SourceRepo is used as the discovery announcement name of
  # all live instances of this application.
  SourceRepo: github.com/someuser/somerepo
  # Owner is the name of the team who own this application's code. It will
  # be used to configure alerting.
  Owner: someteam
  # Kind is the kind of application this is. Currently the only available
  # kind is "http-service" meaning an application that runs indefinitely
  # and responds to HTTP requests on a port provided by the platform.
  # Later we plan to add kinds for cron jobs, on-demand tasks etc.
  Kind: http-service

# Deployments describes how this application should be deployed and configured globally.
# Each member of deployments describes a complete deployment of the applcation for a given
# datacentre. The first item, "Global" describes the deployment in all datacentres. All
# other members provide fine grained per-datacentre overrides.
Deployments:
  # The Global deployment is used for all datacentres. Other datacentre deployments
  # specify overrides per-datacentre. You may optionally not use Global if you only
  # want to deploy to specific datacentres.
  Global:
    Instance:
      Count:  3
      CPUs:   0.05
      Memory: 32MB
    # SourceTag is the tag in the SourceRepo that should be deployed.
    SourceTag: v0.0.5
    # SourceRevision is the revision ID of the above SourceTag. We supply both here
    # so that we have a nice human readable tag, plus an immutable ID of the content
    # contained therein. The SourceRevision must correspond with the SourceTag, according
    # to the SourceRepo.
    SourceRevision: de7bcd8a57274f41c57778d21175ca43f5993157
    # Environment specifies specific environment configuration to add to the execution
    # environment of the applcation. Note that some variables are protected and may not
    # be specified here. Please see /config.yaml for details.
    Environment:
      SOME_ENV_VAR: Hello, somerepo!
  # pp-uswest2 is an override for deployment in the pp-uswest2 datacentre.
  # The settings here are deep-merged over settings from Global.
  north-america:
    Instance:
      Count: 2
      CPUs: 0.1
      Memory: 2GB
    SourceTag: v0.0.6
    SourceRevision: 29d69861de143319b155555f1acf6b91a726d8acf

