---
DockerRegistry: my.docker.registry
DockerLabelPrefix: com.some-company
Packs:
  NodeJS:
    AvailableVersions:
    - Name: 4.2.2
      DefaultImage: my.docker.registry/my-node-base-4.2.2
      TargetImages:
        compile: my.docker.registry/my-node-build-4.2.2
    - Name: 0.12.7
      DefaultImage: my.docker.registry/my-node-base-0.12.7
      TargetImages:
        compile: my.docker.registry/my-node-build-0.12.7
    - Name: 0.10.40
      DefaultImage: my.docker.registry/my-node-base-0.10.40
      TargetImages:
        compile: my.docker.registry/my-node-build-0.10.40
    DockerTags:
    AvailableNPMVersions:
    DefaultNodeVersion: 4.2.2
  Go:
    AvailableVersions:
    - Name: 1.5.1
      DefaultImage: my.docker.registry/my-go-build:latest
      TargetImages:
        app: my.docker.registry/my-ubuntu:latest
    DefaultGoVersion: 1.5.1

# EnvironmentDefs defines environment variables that are guaranteed to be set for
# every instance of every deployment of the named type, in every datacentre.
# Note that variables named here are "protected" and cannot be overidden in per-
# application configurations.
EnvironmentDefs:
  # Universal variables are set for absolutely all services.
  Universal:
    SINGULARITY_URL:
      Type: url
      Desc: The singularity base URL.
    SOME_UNIVERSAL_URL:
      Type: url
      Desc: The description for the universal var.
  # http-service variables are set for services of the kind "http-service"
  http-service:
    PORT0:
      # Automatic means that this value is set by the host platform (currently
      # Mesos) and does not need to be defined in this repository.
      Automatic: true
      Desc: The port provided to apps with the http-service type.
    TASK_HOST:
      Automatic: true
      Desc: The platform-provided host name of the node.

